### ISSUE TITLE
Upgrade from 3.6.2 to 3.7.0 - Redirecting to 404.html

### ISSUE THREAD

**Issue by treg** [dsuryd/dotNetify#246]
We have been using DotNetify since 3.3.1.
Without changing any of our code and after upgrading from 3.6.2 to 3.7.0, dotNetify will auto redirect to 404.html.
However, If I add "dotnetify.react.router.urlPath = null;" before calling connect, everything works as before.

I believe the issue is in dotnetify-vm-router.ts line # 88

Please assist.....

-- our pre-connect setup -- 

import dotnetify from 'dotnetify';
dotnetify.hubServerUrl = document.location.origin + '/' + document.location.pathname.split('/')[1];;
dotnetify.debug = (!process.env.NODE_ENV || process.env.NODE_ENV === 'development');

//added to prevent auto redirect to 404.html
dotnetify.react.router.urlPath = null;

**Comment by dsuryd** [comment]
I just published 3.7.1 to correct the faulty logic.  Let me know it fixes the issue.

**Comment by treg** [comment]
upgraded to 3.7.1;  it works almost :)  
still see "router> routed (404)" in the browser debugger window.

**Comment by dsuryd** [comment]
It's an expected debug message.   The wording may change in the future since it's misleading if you're not using dotNetify routing, but shouldn't be a problem for closing this issue.   Thanks!

**Comment by treg** [comment]
Thank you for the quick turnaround.

Yes, I can live with that erroneous debug message.
